version: '3'

services:
  api:
    build:
      context: ./WebsiteFiles/website_sentimental
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: always 